name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Build
      run: |
        npm ci
        npm run build
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
    
    - name: Deploy to branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -B deploy
        
        npm ci --production
        
        git add -f dist/ node_modules/ package*.json
        git commit -m "Deploy ${{ github.sha }}"
        git push -f origin deploy
